DemoProduct1:
  title: My demo product 1
  description : Simple demo product 1
  price : 22
  quantity : 2

DemoProduct2:
  title: My demo product 2
  description : Simple demo product 2
  price : 56
  quantity : 12

DemoProduct3:
  title: My demo product 3
  description : Simple demo product 3
  price : 7
  quantity : 1
